<?php

/**
 * BaseNubioHelper
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $wikiname
 * @property integer $doctrine_uid
 * @property integer $is_blocked
 * @property integer $is_approved
 * @property string $token
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $NubioRevisions
 * 
 * @method string              getWikiname()       Returns the current record's "wikiname" value
 * @method integer             getDoctrineUid()    Returns the current record's "doctrine_uid" value
 * @method integer             getIsBlocked()      Returns the current record's "is_blocked" value
 * @method integer             getIsApproved()     Returns the current record's "is_approved" value
 * @method string              getToken()          Returns the current record's "token" value
 * @method sfGuardUser         getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getNubioRevisions() Returns the current record's "NubioRevisions" collection
 * @method NubioHelper         setWikiname()       Sets the current record's "wikiname" value
 * @method NubioHelper         setDoctrineUid()    Sets the current record's "doctrine_uid" value
 * @method NubioHelper         setIsBlocked()      Sets the current record's "is_blocked" value
 * @method NubioHelper         setIsApproved()     Sets the current record's "is_approved" value
 * @method NubioHelper         setToken()          Sets the current record's "token" value
 * @method NubioHelper         setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * @method NubioHelper         setNubioRevisions() Sets the current record's "NubioRevisions" collection
 * 
 * @package    nubio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNubioHelper extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nubio_helper');
        $this->hasColumn('wikiname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('doctrine_uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_blocked', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('is_approved', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('token', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'doctrine_uid',
             'foreign' => 'id'));

        $this->hasMany('NubioRevision as NubioRevisions', array(
             'local' => 'id',
             'foreign' => 'helper_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}