<?php

/**
 * BaseNubioRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $helper_id
 * @property integer $topic_id
 * @property blob $text
 * @property string $comment
 * @property blob $props
 * @property NubioHelper $NubioHelper
 * @property Doctrine_Collection $NubioTopics
 * 
 * @method integer             getHelperId()    Returns the current record's "helper_id" value
 * @method integer             getTopicId()     Returns the current record's "topic_id" value
 * @method blob                getText()        Returns the current record's "text" value
 * @method string              getComment()     Returns the current record's "comment" value
 * @method blob                getProps()       Returns the current record's "props" value
 * @method NubioHelper         getNubioHelper() Returns the current record's "NubioHelper" value
 * @method Doctrine_Collection getNubioTopics() Returns the current record's "NubioTopics" collection
 * @method NubioRevision       setHelperId()    Sets the current record's "helper_id" value
 * @method NubioRevision       setTopicId()     Sets the current record's "topic_id" value
 * @method NubioRevision       setText()        Sets the current record's "text" value
 * @method NubioRevision       setComment()     Sets the current record's "comment" value
 * @method NubioRevision       setProps()       Sets the current record's "props" value
 * @method NubioRevision       setNubioHelper() Sets the current record's "NubioHelper" value
 * @method NubioRevision       setNubioTopics() Sets the current record's "NubioTopics" collection
 * 
 * @package    nubio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNubioRevision extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nubio_revision');
        $this->hasColumn('helper_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('text', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('props', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NubioHelper', array(
             'local' => 'helper_id',
             'foreign' => 'id'));

        $this->hasMany('NubioTopic as NubioTopics', array(
             'local' => 'id',
             'foreign' => 'revision_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}