<?php

/**
 * NubioTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NubioTopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NubioTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NubioTopic');
    }
    
    public static function routingQuery( $query ) {
    	return $query
	      ->leftJoin('a.NubioRevision r')
	      ->leftJoin('a.NubioCategory c')
	      ->innerJoin('r.NubioHelper h')
	      ->innerJoin('h.sfGuardUser u ON a.id = r.topic_id')
	      ->execute();
    }
    
    public static function createBaseQuery() {
    	return self::getInstance()
	      ->createQuery('t')
	      ->leftJoin('t.NubioRevision r')
	      ->leftJoin('t.NubioCategory c')
	      ->innerJoin('r.NubioHelper h')
	      ->innerJoin('h.sfGuardUser u ON t.id = r.topic_id');
    }
    
    public function getTopicFromID( $id ) {
    	return self::createBaseQuery()->where( 't.id = ?', $id )->fetchOne();
    }
    
	static public function getLuceneIndex() {
		ProjectConfiguration::registerZend();
	
		if (file_exists($index = self::getLuceneIndexFile())) {
			return Zend_Search_Lucene::open($index);
		}
	
		return Zend_Search_Lucene::create($index);
	}
	
	static public function getLuceneIndexFile() {
		return sfConfig::get('sf_data_dir').'/topic.'.sfConfig::get('sf_environment').'.index';
	}
	
	public function getForLuceneQueryBase($query) {
		$hits = self::getLuceneIndex()->find($query);
		
		$pks = array();
		foreach ($hits as $hit) {
			$pks[] = $hit->pk;
		}
		
		if( !count( $hits ) ) {
			return self::createBaseQuery()->where( '1 = 2' );
		}
		
		$q = self::createBaseQuery()
			->whereIn('t.id', $pks)
			->limit(20);
		return $q;
		
	}
	
	public function getForLuceneQuery($query) {
		return $this->getForLuceneQueryBase($query)->execute();
	}
}