<?php

/**
 * NubioHelperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NubioHelperTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NubioHelperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NubioHelper');
    }
    
    public static function routingQuery( $query ) {
    	return $query
	      ->innerJoin('a.sfGuardUser g ON a.doctrine_uid = g.id')
	      ->execute();
    }
    
    public static function createBaseQuery() {
    	return self::getInstance()
	      ->createQuery('h')
	      ->innerJoin('h.sfGuardUser g ON h.doctrine_uid = g.id');
    }
    
    public function getHelperList() {
    	return self::createBaseQuery()->execute();
    }
    
    public function getUnapprovedList() {
    	return self::createBaseQuery()
    		->where( 'h.is_approved = 0' );
    }
    
    public function getFromDoctrineUID( $uid ) {
    	return self::createBaseQuery()
    		->where( 'h.doctrine_uid = ?', $uid )
    		->fetchOne();
    }
    
    public function getFromDoctrineUsername( $username ) {
    	return self::createBaseQuery()
    		->where( 'g.username = ?', $username )
    		->fetchOne();
    }
    
    public function getFromDoctrineEmail( $email ) {
    	return self::createBaseQuery()
    		->where( 'g.email_address = ?', $email )
    		->fetchOne();
    }
}