<?php

/**
 * NubioRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nubio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NubioRevision extends BaseNubioRevision
{
	
	public function getRevisionsQuery() {
		return Doctrine_Core::getTable('NubioTopic')
			->createBaseQuery()
			->where( 'c.id = ?', $cat_id );
	}
	
	public function getPreviousRevision() {
    	$q = Doctrine_Core::getTable('NubioRevision')
    		->createQuery('r')
    		->where( 'r.topic_id = ?', $this->getTopicId() )
    		->fetchArray();
    	
    	$old = $q[0];
    	foreach( $q as $row ) {
    		if( $row['id'] == $this->getId() ) return $old['id'];
    		$old = $row;
    	}
    	return 1;
    }
}
