<?php

/**
 * NubioCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NubioCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NubioCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NubioCategory');
    }
    
    public function getCategoryList() {
    	return self::getInstance()->createQuery('c')->execute();
    }
    
    public function getTopicListFromID( $id ) {
    	return Doctrine_Core::getTable( 'NubioTopic' )
    		->createBaseQuery()
    		->where( 'c.id = ?', $id )
    		->execute();
    }
    
    public function fetchFormArray() {
    	$catchoices = function($value) {
			$value2 = array();
			foreach( $value as $key => $val ) {
				$value2[$key + 1] = $val;
			}
			return $value2;
		};
		$catchoices = $catchoices(array_map( 
			function ($value) {
	    		return $value['name'];
	  		},  
	  		self::getInstance()->createQuery('catquery')->fetchArray() 
	  	));
	  	return $catchoices;  	
    }
    
}