<?php

/**
 * NubioCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nubio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NubioCategory extends BaseNubioCategory
{

	public function getTopicsFromCategoryID( $cat_id, $limit = 10 ) {
		$query = $this->getCategoryQueryFromID( $cat_id )
			->limit($limit)
			->execute();
		return $query;
	}
	
	public function getTopicCountFromCategoryID( $cat_id ) {
		$query = $this->getCategoryQueryFromID( $cat_id )
			->count();
		return $query;
	}
	
	public function getCategoryQueryFromID( $cat_id ) {
		return Doctrine_Core::getTable('NubioTopic')
			->createBaseQuery()
			->where( 'c.id = ?', $cat_id );
	}
}
