generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NubioTopic
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          nubio_topic
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Topic management
        display: [=id, =summary, revision_id, category]
        max_per_page: 10
      filter:  ~
      form:
        display:
          Content: [summary, answer, keywords, comment]
          Admin:   [is_deleted]
      edit:
        title: Editing topic #%%id%%
      new:
        title: New topic
