generator:
  class: sfDoctrineGenerator
  param:
    model_class:           NubioRevision
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          nubio_revision
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=id, topic_id, helper_id]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
